grafana:
  client:
    secret: ENC[AES256_GCM,data:OC8jIpXbOtXNiEqEn9QWjHlvq7JgH5Dv+/OkJsqfia0=,iv:XzBg2X2eLmlJKACgxKZPu60Rr+sGEg39B2Vb0CRfMX8=,tag:mNehDdfnIJ1tb9bHUT02zQ==,type:str]
sops:
  age:
    - recipient: age1h6la0udmehtp6h5z0ak0sz6a5phwtpyfk4uad2qztydy8mudrawslk5y3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TVkzaXlpV0dyWGs1ZEh5
        anAyejNyRWtXdXJ1bG1PU1MzdHBPY1dNSFRBCnFyMTY0OXdEQ2ZsT2s1RzFDS2I2
        WTZrd1ZSNld4ajlvbm05MDdWa1paQTQKLS0tIDhBWEo1WlNRd0tFVzZIeFhWdnFQ
        YmFkOXFCZ0JWUXZaZGdrSDE1cTY5TzAKxBuWvDpxBtnx+/DrDVuSJfY2icBEC5Z7
        u4lTPVpe6k7W5ylEoR/umwoZkwTfBogH8vTfyomMkwASaBe258KK3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T06:30:39Z"
  mac: ENC[AES256_GCM,data:9m/b2EomiiGi501MqW+GSY5VCvtbnflKHUMWCw4tR8uGxXVeIHCFQMQcv90VM1nL3+RW9/lrncPYnZxEDneQ+O4YZoDvVnW+tNycO5ejRAN9rC4TyurAtohWZzvqw4jpqyoOOEtwfEjf8ePs9aczWTc7HFjqblMjwgjbYP/jLAY=,iv:69LOW902K/lSxt+ao+cHELysfqtgUOEzH2fnr/Wsfvc=,tag:HUkVo0AJWXqR5Y8khuiStw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
